// Generated by FlutterFire CLI. Run:
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// Replace this file with the output of that command.
// DO NOT commit real keys to version control.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmJ-yygctaNvDmeq2euaJnoQVn_Ltyjk',
    appId: '1:235381544962:android:99993490ed0aee69c4ef1b',
    messagingSenderId: '235381544962',
    projectId: 'ayma-ai',
    storageBucket: 'ayma-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOMlRq9ufK-V6LSkJ6wiD7Vxex0VgwBhc',
    appId: '1:235381544962:ios:8d9dfb229f63f9c1c4ef1b',
    messagingSenderId: '235381544962',
    projectId: 'ayma-ai',
    storageBucket: 'ayma-ai.firebasestorage.app',
    iosBundleId: 'com.ayma.aymaFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3aRYAZFaBwPPk17FoZ242y6NE5-C70QE',
    appId: '1:235381544962:web:a6b099d7249da59ac4ef1b',
    messagingSenderId: '235381544962',
    projectId: 'ayma-ai',
    authDomain: 'ayma-ai.firebaseapp.com',
    storageBucket: 'ayma-ai.firebasestorage.app',
  );

}
